### PR TITLE
Finished translation: Brazilian Portuguese

### PR DESCRIPTION
**Pull request by gustavohmsilva**

### CODE REVIEW

**Comment by JMoerman** [comment]
Thanks for the pull request!
It may be easier to update translations via https://translations.launchpad.net/go-for-it.

**Comment by gustavohmsilva** [comment]
I don't feel comfortable with those kind of tools. Transifex for example, always break some punctuation that are characteristics of Brazilian Portuguese. Doing it by hand usually gives me more control and I rather enjoy it working directly more. Hope u don't mind.

**Comment by JMoerman** [comment]
As long as I don't get flooded with pull requests, I don't have an issue with it.
Launchpad is currently set up to automatically import code and translations, so translations are kept in sync. (I currently have to export the translations to GitHub manually.)

**Comment by gustavohmsilva** [comment]
You won't, don't worry. The translation is completely done and revised (Brazilian Portuguese at least), and you won't receive any pull request for me anymore (unless a new version add sentences that need translation of course) 👍

**Pull request merged**
